void MicroStart(void){
	   //  INTIALIZE PORT A     pin2 , pin3 , pin4 , pin5 
	
	SYSCTL_RCGCGPIO_R |= 0x01;     // ENABLE CLOCK OF PORT F
while ((SYSCTL_PRGPIO_R&0x01) == 0){};  //CHECK FLAG
GPIO_PORTA_CR_R |= 0x2C;          // ENABLE THE CHANGES  ON PIN2 PIN3 PIN4  
GPIO_PORTA_DIR_R |= 0x2C;         //  OUTPUTS PINS 
GPIO_PORTA_DEN_R |= 0x2C;         // DIGITAL PINS 
GPIO_PORTA_AMSEL_R &= ~0x2C;       // DISABLE ANALOG SIGNAL 
GPIO_PORTA_AFSEL_R &=~0x2C;           // DISABLE ALTERNATE FUNCTION SELECTION  
GPIO_PORTA_PCTL_R &= ~0x00FFFF00;     // OUTPUT PINS 
GPIO_PORTA_DATA_R &= ~0x2C;           // START WITH ZERO VALUE 
	
	/* INTIALIZE PORT B    pin0 , pin1 , pin2 */
	SYSCTL_RCGCGPIO_R |= 0x02;     // ENABLE CLOCK OF PORT F
while ((SYSCTL_PRGPIO_R&0x02) == 0){};  //CHECK FLAG
GPIO_PORTB_CR_R = 0xFF;          // ENABLE THE CHANGES  ON PIN2 PIN3 PIN4  
GPIO_PORTB_DIR_R = 0xFF;         //  OUTPUTS PINS 
GPIO_PORTB_DEN_R = 0xFF;         // DIGITAL PINS 
GPIO_PORTB_AMSEL_R &= ~0xFF;       // DISABLE ANALOG SIGNAL 
GPIO_PORTB_AFSEL_R &=~0xFF;           // DISABLE ALTERNATE FUNCTION SELECTION  
GPIO_PORTB_PCTL_R &= ~0xFFFFFFFF;     // OUTPUT PINS 
GPIO_PORTB_DATA_R  =0x00;           // START WITH ZERO VALUE 
	
	
	
	
	    // INTIALIZE PORT E    pin0  : , pin1 :     
		SYSCTL_RCGCGPIO_R |= 0x10;     // ENABLE CLOCK OF PORT F
while ((SYSCTL_PRGPIO_R&0x10) == 0){};  //CHECK FLAG
GPIO_PORTE_CR_R |= 0x03;          // ENABLE THE CHANGES  ON PIN2 PIN3 PIN4  
GPIO_PORTE_DIR_R |= 0x02;         // INPUT PIN0 OUTPUTS PIN1 
GPIO_PORTE_DEN_R |= 0x02;         // DIGITAL PINS 
GPIO_PORTE_AMSEL_R &= ~0x03;       // DISABLE ANALOG SIGNAL 
GPIO_PORTE_AFSEL_R |=0x03;           // ENABLE ALTERNATE FUNCTION SELECTION  
GPIO_PORTE_PCTL_R |= 0x00000011;     // RX AND TX  
GPIO_PORTE_DATA_R = 0x00;           // START WITH ZERO VALUE 
	

		SYSCTL_RCGCGPIO_R |= 0x08;     // ENABLE CLOCK OF PORT F
while ((SYSCTL_PRGPIO_R&0x08) == 0){};  //CHECK FLAG
GPIO_PORTD_CR_R |= 0xFF;          // ENABLE THE CHANGES  ON PIN2 PIN3 PIN4  
GPIO_PORTD_DIR_R |= 0xFF;         //  OUTPUTS PINS 
GPIO_PORTD_DEN_R |= 0xFF;         // DIGITAL PINS 
GPIO_PORTD_AMSEL_R &= ~0xFF;       // DISABLE ANALOG SIGNAL 
GPIO_PORTD_AFSEL_R &=~0xFF;           // DISABLE ALTERNATE FUNCTION SELECTION  
GPIO_PORTD_PCTL_R &= ~0xFFFFFFFF;     // OUTPUT PINS 
GPIO_PORTD_DATA_R  |=0xFF;           // START WITH ZERO VALUE 
	

}